# Generated by Django 5.2.3 on 2025-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("product", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.FloatField()),
            ],
        ),
    ]
