# Generated by Django 5.2.3 on 2025-06-22 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_uploadhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
