# Generated by Django 5.2.3 on 2025-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_sale_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="filename",
            field=models.CharField(default="", max_length=255),
        ),
    ]
