# Generated by Django 5.2.3 on 2025-06-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_sale_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadhistory",
            name="records_count",
            field=models.IntegerField(default=0),
        ),
    ]
